development:
  adapter: redis #async
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

test:
  adapter: test

production:
  adapter: async
#  adapter: redis
#  url: <%#=ENV['REDISTOGO_URL']%>
#  <%#= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#  channel_prefix: server_production
